In [15]:
import pandas as pd
data=pd.read_excel('/home/aayan/Downloads/data.xlsx')
data

,num_removed_atoms,num_ZZ_atoms,num_AC_atoms,num_UA_atoms,num_SB_atoms,count_rim_atoms,num_incomplete_hexagons,num_5_membered_rings,max_dist,shape_factor,...,240_clock_rot,300_clock_rot,mirror_vertical,mirror_90_clock_vertical,mirror_150_clock_vertical,mirror_30_clock_vertical,mirror_60_clock_vertical,mirror_120_clock_vertical,time,probability
0,4,6,0,0,0,18,6,2,9.328612,0.679395,...,0,0,0,0,0,0,0,0,78.229,0.3956
1,4,4,2,0,0,18,6,2,7.527692,0.841933,...,0,0,0,1,0,0,0,0,78.229,0.4037
2,4,6,0,0,0,18,6,3,7.527692,0.841933,...,1,0,1,0,0,0,1,1,78.229,0.2007
3,5,5,2,0,0,20,7,3,9.328612,0.733831,...,0,0,0,0,0,0,0,0,94.874,0.4709
4,5,5,0,0,1,19,7,2,7.527692,0.909392,...,0,0,1,0,0,0,0,0,93.917,0.1411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20835,22,8,8,2,0,42,21,4,16.406224,0.722711,...,0,0,0,0,0,0,0,0,211.380,0.0001
20836,22,7,6,1,1,37,20,4,14.852380,0.779081,...,0,0,0,0,0,0,0,0,216.510,0.0001
20837,22,6,8,0,1,37,20,4,14.010985,0.825867,...,0,0,0,0,0,0,0,0,212.730,0.0001
20838,22,8,8,0,0,38,20,2,17.306676,0.668598,...,0,0,0,0,0,0,0,0,204.320,0.0001
20839,22,10,4,0,1,37,20,3,18.162541,0.637092,...,0,0,0,0,0,0,0,0,212.620,0.0001

In [18]:
import numpy as np
from sklearn.linear_model import LinearRegression
X=data.drop(columns=['time','probability'])

In [21]:
y1=data['time']
y2=data['probability']
reg1=LinearRegression().fit(X,y1)
reg1.score(X,y1)

0.9312836016269951

In [9]:
import pandas as pd
data=pd.read_csv('/home/aayan/Downloads/T_1_894.csv')
data

   distance     DE
0        10  0.001
1        15  0.010
2        20  0.585
3        25  0.885
4        30  1.085
5        35  5.075
6        40  5.485
7        44  5.595
8        50  5.595

In [20]:
import numpy as np
from sklearn.linear_model import LinearRegression
X=data.drop(columns=['DE'])
y1=data['distance']
y2=data['DE']
reg1=LinearRegression().fit(X,y2)
reg1.score(X,y1)
reg1.coef_

array([0.17860749])

In [24]:
reg1.intercept_
ypred2=reg1.predict(X)
ypred2
import sklearn
sklearn.metrics.mean_absolute_error(y2,ypred2)

0.8137867418710446